apiVersion: v1
kind: Pod
metadata:
  name: sanity-fm-ql-alpha-1
spec:
  restartPolicy: Never 
  securityContext:
    runAsUser: 272115
    runAsGroup: 1132
  containers:
    - name: simplenotebook
      # image: quay.io/jupyter/minimal-notebook:latest
      image: pytorch/pytorch:1.7.1-cuda11.0-cudnn8-devel
      volumeMounts: 
        # - name: d10
        #   mountPath: /sciclone/data10/hmeng
        - name: nsf
          mountPath: /workspace
      command: 
        - /bin/bash
        - -c
        - |
          eval "$(conda shell.bash hook)"
          conda activate /workspace/.conda/envs/diffusionRL
          cd /workspace/research/DC3
          echo "Running from $(pwd)"
          #python
          # python method_6.py --useSanity=True --useWandb=True --useCompl=True --diffusion_beta_start=0.01 --diffusion_beta_end=0.20 --n_timesteps=5
          # python method_6.py --useSanity=True --useWandb=True --useCompl=True --diffusion_beta_start=0.01 --diffusion_beta_end=0.30 --n_timesteps=5
          # python method_6.py --useSanity=True --useWandb=True --useCompl=True --diffusion_beta_start=0.01 --diffusion_beta_end=0.40 --n_timesteps=5
          # python method_6.py --useSanity=True --useWandb=True --useCompl=True --diffusion_beta_start=0.01 --diffusion_beta_end=0.50 --n_timesteps=5
          # python method_6.py --useSanity=True --useWandb=True --useCompl=True --diffusion_beta_start=0.05 --diffusion_beta_end=0.20 --n_timesteps=5
          # python method_6.py --useSanity=True --useWandb=True --useCompl=True --diffusion_beta_start=0.05 --diffusion_beta_end=0.30 --n_timesteps=5
          # python method_6.py --useSanity=True --useWandb=True --useCompl=True --diffusion_beta_start=0.05 --diffusion_beta_end=0.40 --n_timesteps=5
          # python method_6.py --useSanity=True --useWandb=True --useCompl=True --diffusion_beta_start=0.05 --diffusion_beta_end=0.50 --n_timesteps=5
          # python data_checker.py --useSanity=True --useWandb=True --useCompl=True --alpha=0.0 --beta=1.0
          # python method_7.py --useSanity=True --useWandb=True --useCompl=True --alpha=0.01
          # python method_7.py --useSanity=True --useWandb=True --useCompl=True --alpha=0.001
          python method_7.py --useSanity=True --useWandb=True --useCompl=True --alpha=0.1
      resources:
        limits:
          memory: "40Gi"
          cpu: 12
          nvidia.com/gpu: 1
      # securityContext:
      #   runAsUser: 272115
      #   runAsGroup: 1132
  nodeSelector:
    nvidia.com/gpu.product: "NVIDIA-A40"
    # owner: hchen
    #kubernetes.io/hostname: gu07.sciclone.wm.edu
  volumes:
    - name: nsf
      nfs:
        server: 128.239.56.166
        path: /sciclone/home/hmeng/
    # - name: d10
    #   nfs:
    #     server: 128.239.56.30
    #     path: /sciclone/data10/hmeng


 
 
